services:
    Maps_red\TicketingBundle\Form\CreateTicketForm:
        tags:
            - { name: form.type }

    Maps_red\TicketingBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Maps_red\TicketingBundle\Form\TicketForm:
        tags:
            - { name: form.type }

    Maps_red\TicketingBundle\Maker\MakeTicketing:
        arguments: ["@maker.file_manager"]
        tags:
            - { name: maker.command }

    Maps_red\TicketingBundle\Manager\TicketManager:
        tags:
            - { name: ticketing.manager, class: 'ticket', enable_history: true}

    Maps_red\TicketingBundle\Manager\TicketCategoryManager:
        tags:
            - { name: ticketing.manager, class: 'ticket_category'}

    Maps_red\TicketingBundle\Manager\TicketCommentManager:
        tags:
            - { name: ticketing.manager, class: 'ticket_comment'}

    Maps_red\TicketingBundle\Manager\TicketHistoryManager:
        tags:
            - { name: ticketing.manager, class: 'ticket_history'}

    Maps_red\TicketingBundle\Manager\TicketKeywordManager:
        tags:
            - { name: ticketing.manager, class: 'ticket_keyword'}

    Maps_red\TicketingBundle\Manager\TicketStatusManager:
        tags:
            - { name: ticketing.manager, class: 'ticket_status', default_status_name: true}

    Maps_red\TicketingBundle\EventSubscriber\RequestSubscriber:
        autowire: true
        tags:
            - { name: kernel.event_subscriber }

    Maps_red\TicketingBundle\EventSubscriber\TicketHistorySubscriber:
        autowire: true
        arguments:
            $enableHistory: "%ticketing.enable_history%"
        tags:
            - { name: kernel.event_subscriber }


