services:
    Maps_red\TicketingBundle\Form\CreateTicketForm:
        tags:
            - { name: form.type }

    Maps_red\TicketingBundle\Form\TicketForm:
        tags:
            - { name: form.type }

    Maps_red\TicketingBundle\Maker\MakeTicketing:
        arguments: ["@maker.file_manager"]
        tags:
            - { name: maker.command }

    Maps_red\TicketingBundle\Manager\TicketManager:
        tags:
            - { name: ticketing.manager, class: 'ticket', default_status_name: true, enable_history: true}

    Maps_red\TicketingBundle\Manager\TicketHistoryManager:
        tags:
            - { name: ticketing.manager, class: 'ticket_history'}

    Maps_red\TicketingBundle\EventSubscriber\RequestSubscriber:
        autowire: true
        tags:
            - { name: kernel.event_subscriber }

    Maps_red\TicketingBundle\EventSubscriber\TicketHistorySubscriber:
        autowire: true
        tags:
            - { name: kernel.event_subscriber }


